apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster01
  region: us-east-1
  version: "1.25"

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.small
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        # Allow EBS Volumes with new (v1.23) CSI driver
        ebs: true

        # Write access to ECR
        imageBuilder: true

        # Allow workers to send data to CloudWatch
        cloudWatch: true
      attachPolicyARNs:
        # Required by EKS workers
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        # For our Application
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess

addons:
  - name: aws-ebs-csi-driver
    version: latest

